# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CartAGen4QGIS
                                 A QGIS plugin
 Cartographic generalization
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-11
        copyright            : (C) 2023 by Guillaume Touya, Justin Berli & Paul Bourcier
        email                : guillaume.touya@ign.fr
 ***************************************************************************/
"""

__author__ = 'Guillaume Touya, Justin Berli & Paul Bourcier'
__date__ = '2023-05-11'
__copyright__ = '(C) 2023 by Guillaume Touya, Justin Berli & Paul Bourcier'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (
    QgsProcessing, QgsFeatureSink, QgsProcessingAlgorithm,
    QgsFeature, QgsGeometry, QgsProcessingParameterDefinition, QgsWkbTypes
)
from qgis.core import (
    QgsProcessing,
    QgsFeatureSink, 
    QgsProcessingAlgorithm,
    QgsFeature,
    QgsGeometry,
    QgsProcessingParameterDefinition,
    QgsProcessingParameterFeatureSource, 
    QgsProcessingParameterFeatureSink, 
    QgsProcessingParameterNumber,
    QgsProcessingParameterDistance,
    QgsProcessingParameterEnum,
    QgsProcessingParameterBoolean,
    QgsProcessingException,
    QgsProcessingParameterMultipleLayers
)

class CatmullRomSmoothing(QgsProcessingAlgorithm):
    """
    Smooth a line or polygon and preserve vertexes.

    This algorithm was proposed by Catmull and Rom, this is the version proposed by Barry and Goldman 
    that makes use of the de Boor’s algorithm for evaluating spline curves in B-spline form.

    Catmull-Rom splines are a family of cubic interpolating splines that pass through all control points. 
    The alpha parameter controls the type of parameterization: 0 for uniform, 0.5 for centripetal (default), and 1 for chordal. 
    Centripetal parameterization avoids cusps and self-intersections.

    Parameters:
        line (LineString) – The line to smooth.

        subdivisions (int, optional) – Number of interpolated points between each pair of control points. Default is 10. Higher values produce smoother curves.

        alpha (float, optional) – Parameterization type. Default is 0.5 (centripetal):

            0.0: uniform parameterization

            0.5: centripetal parameterization (recommended, prevents loops)

            1.0: chordal parameterization

    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    
    INPUT = 'INPUT'

    SUBDIVISIONS = 'SUBDIVISIONS'
    ALPHA = 'ALPHA'
 
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth Catmull-Rom'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth lines and patches'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[3]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        helpstring = """
            <b>/!\Doesn't work with multipart geometry/!\</b>
            <b>/!\You need to drop Z and M for the algorithm to function/!\</b>

            Smooth a line or polygon and preserve vertexes.
            This algorithm was proposed by Catmull and Rom, this is the version proposed by Barry and Goldman that makes use of the de Boor’s algorithm for evaluating spline curves in B-spline form.
            <h3> Parameters: </h3>
            <ul>
                <li> - <em>Subdivisions</em> : Number of interpolated points between each pair of control points. Higher values produce smoother curves.</li>
                <li> - <em>Alpha</em> : Parameterization type:</li>
                <ul>
                    <li>  . Uniform parameterization </li>
                    <li>  . Centripetal parameterization (recommended, prevents loops) </li>
                    <li>  . Chordal parameterization </li>
                <ul>
            </ul>

            For more see <a href="https://cartagen.readthedocs.io/en/latest/reference/cartagen.smooth_catmull_rom.html#cartagen.smooth_catmull_rom">help online</a>.
            """
        return self.tr(helpstring)
        
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return CatmullRomSmoothing()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input lines or polygons :'),
                [QgsProcessing.TypeVectorPolygon, QgsProcessing.TypeVectorLine]
            )
        )

        subdivisions = QgsProcessingParameterNumber(
            self.SUBDIVISIONS,
            self.tr('Subdivisions :'),
            type=QgsProcessingParameterNumber.Integer,
            defaultValue=10,
            optional=False
        )
        self.addParameter(subdivisions)

        listAlpha = ['Centrepital Parametrization','Uniform parametrization', 'Chordal parametrization']
        alpha = QgsProcessingParameterEnum(
            self.ALPHA,
            self.tr('Alpha :'),
            options = listAlpha,
            defaultValue = 'Centrepital Parametrization'
        )
        alpha.setFlags(alpha.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(alpha)

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Smoothed Catmull-Rom')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import smooth_catmull_rom
        from cartagen4qgis.src.tools import list_to_qgis_feature_2
        from shapely import Polygon
        from shapely.wkt import loads

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        
        # retrieve the other parameters values
        subdivisions = self.parameterAsInt(parameters, self.SUBDIVISIONS, context)
        alpha = self.parameterAsEnum(parameters, self.ALPHA, context)
        dico = {0:0.5, 1:0.0, 1:1}

        #Using CartAGen algorithm and transforming the result to a list of QgsFeature()
        #Depending on the type of geometry of the input data
        if source.wkbType().name == 'Polygon':
            gs = gdf.copy()
            for i in range(len(gdf)):
                try:
                    gs.loc[i,'geometry'] = smooth_catmull_rom(list(gs.geometry)[i], alpha=dico[alpha], subdivisions=subdivisions)
                except:
                    gs.loc[i,'geometry'] = gs.loc[i,'geometry']
            # Update the progress bar
            feedback.setProgress(int(i* total))
                
            res = gs.to_dict('records')
            res = list_to_qgis_feature_2(res,source.fields())

        else:
            gs = gdf.copy()

            for i in range(len(gdf)):
                geommultiple = gs.loc[i,'geometry']
                listGeomSimple = list(geommultiple.geoms)
                listeTraitee = []

                for ligne in listGeomSimple:
                    ligneTraitee = smooth_catmull_rom(ligne, alpha=dico[alpha], subdivisions=subdivisions)
                    listeTraitee.append(ligneTraitee)

                # Update the progress bar
                feedback.setProgress(int(i * total))

                gs.loc[i,'geometry'] = listeTraitee
            
            res = gs.to_dict('records')
            res = list_to_qgis_feature_2(res,source.fields())

        # Create the output sink    
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, res[0].fields(), source.wkbType(), source.sourceCrs())
        
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        return {
            self.OUTPUT: dest_id
        }

class ChaikinSmoothing(QgsProcessingAlgorithm):
    """
    Smooth a line or polygon by cutting corners.

    This algorithm was proposed by Chaikin [1] and this version makes use of the equivalent multi-step algorithm introduced by Wu et al. .
    It is a simple subdivision scheme that repeatedly cuts corners of a line or polygon. Each iteration doubles the number of vertices 
    and produces a smoother curve that converges to a quadratic B-spline.

    Parameters:
        line (LineString) – The line to smooth.

        iterations (int, optional) – Number of subdivision iterations (k parameter). Default is 3. Each iteration doubles the number of vertices (2^k ITERATIONS per segment).

        keep_ends (bool, optional) – Whether to keep the original endpoints fixed for open lines. Default is True. For closed geometries, this parameter is ignored and corners are always cut.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    
    INPUT = 'INPUT'

    ITERATIONS = 'ITERATIONS'
    KEEP_ENDS = 'KEEP_ENDS'
 
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth Chaikin'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth lines and patches'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[0]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        helpstring = """
            Smooth a line or polygon by cutting corners.
            This algorithm was proposed by Chaikin and this version makes use of the equivalent multi-step algorithm introduced by Wu et al.
            It is a simple subdivision scheme that repeatedly cuts corners of a line or polygon. Each iteration doubles the number of vertices and produces a smoother curve that converges to a quadratic B-spline.
            <h3> Parameters: </h3>
            <ul>
                <li> - <em>Iterations</em> : Number of subdivision iterations (k parameter). Each iteration doubles the number of vertices (2^k subdivisions per segment).</li>
                <li> - <em>Keep ends</em> : Whether to keep the original endpoints fixed for open lines. For closed geometries, this parameter is ignored and corners are always cut.</li>
            </ul>
            For more see <a href="https://cartagen.readthedocs.io/en/latest/reference/cartagen.smooth_chaikin.html#cartagen.smooth_chaikin">help online</a>.
        """
        return self.tr(helpstring)
        
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return ChaikinSmoothing()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input lines or polygons :'),
                [QgsProcessing.TypeVectorPolygon, QgsProcessing.TypeVectorLine]
            )
        )

        iterations = QgsProcessingParameterNumber(
            self.ITERATIONS,
            self.tr('Iterations :'),
            type=QgsProcessingParameterNumber.Integer,
            defaultValue=3,
            optional=False
        )
        self.addParameter(iterations)

        keep_ends = QgsProcessingParameterBoolean(
            self.KEEP_ENDS,
            self.tr('Keep ends ?'),
            defaultValue=True,
            optional=False
        )
        self.addParameter(keep_ends)

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Smoothed Chaikin')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import smooth_chaikin
        from cartagen4qgis.src.tools import list_to_qgis_feature_2
        from shapely import Polygon
        from shapely.wkt import loads

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        
        # retrieve the other parameters values
        iterations = self.parameterAsInt(parameters, self.ITERATIONS, context)
        keep_ends = self.parameterAsBoolean(parameters, self.KEEP_ENDS, context)

        #Using CartAGen algorithm and transforming the result to a list of QgsFeature()
        #Depending on the type of geometry of the input data
        if source.wkbType().name == 'Polygon':

            gs = gdf.copy()
            for i in range(len(gdf)):
                gs.loc[i,'geometry'] = smooth_chaikin(list(gs.geometry)[i], iterations=iterations, keep_ends=keep_ends)
                feedback.setProgress(int(i* total))

            res = gs.to_dict('records')
            res = list_to_qgis_feature_2(res,source.fields())

        else:
            gs = gdf.copy()
            for i in range(len(gdf)):
                geommultiple = gs.loc[i,'geometry']
                listGeomSimple = list(geommultiple.geoms)
                listeTraitee = []

                for ligne in listGeomSimple:
                    ligneTraitee = smooth_chaikin(ligne, iterations=iterations, keep_ends=keep_ends)
                    listeTraitee.append(ligneTraitee)
                    feedback.setProgress(int(i* total))

                gs.loc[i,'geometry'] = listeTraitee

            res = gs.to_dict('records')
            res = list_to_qgis_feature_2(res,source.fields())

        # Create the output sink    
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, res[0].fields(), source.wkbType(), source.sourceCrs())
        
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        return {
            self.OUTPUT: dest_id
        }
    
class GaussianSmoothing(QgsProcessingAlgorithm):
    """
    Smooth a line and attenuate its inflexion points.
    The gaussian smoothing has been studied by Babaud et al. for image processing,
    and by Plazanet for the generalisation of cartographic features.

    Parameters:
        line (LineString) – The line to smooth.

        sigma (float, optional) – Gaussian filter strength. Default value to 30, which is a high value.

        sample (float, optional) – The length in meter between each nodes after resampling the line. If not provided, the sample is derived from the line and is the average distance between each consecutive vertex.

        densify (bool, optional) – Whether the resulting line should keep the new node density. Default to True.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    SIGMA = 'SIGMA'
    SAMPLE = 'SAMPLE'
    DENSIFY = 'DENSIFY'
 
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth Gaussian'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth lines and patches'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[3]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        helpstring = """
            <b>/!\Doesn't work with multipart geometry/!\</b>
            <b>/!\You need to drop Z and M for the algorithm to function/!\</b>

            Smooth a line and attenuate its inflexion points.
            The gaussian smoothing has been studied by Babaud et al. for image processing, and by Plazanet for the generalisation of cartographic features.
            Accept Multi geometries. If a polygon is provided, it also apply the smoothing to its holes using the same parameters.
            <h3> Parameters: </h3>
            <ul>
                <li> - <em>Sigma</em> : Gaussian filter strength. Default value to 30, which is a high value.</li>
                <li> - <em>Sample</em> : The length in meter between each nodes after resampling the geometry. If not provided, the sample is derived from the geometry and is the average distance between each consecutive vertex.</li>
                <li> - <em>Densify</em> : Whether the resulting geometry should keep the new vertex density. Default to True.</li>
            </ul>
            For more see <a href=" https://cartagen.readthedocs.io/en/latest/reference/cartagen.smooth_gaussian.html#cartagen.smooth_gaussian">help online</a>.
        """
        
        return self.tr(helpstring)
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return GaussianSmoothing()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('The geometry to smooth :'),
                [QgsProcessing.TypeVectorPolygon, QgsProcessing.TypeVectorLine]
            )
        )

        sigma = QgsProcessingParameterNumber(
            self.SIGMA,
            self.tr('Sigma :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=30.0,
            optional=False
        )
        self.addParameter(sigma)
       
        densify = QgsProcessingParameterBoolean(
            self.DENSIFY,
                self.tr('Densify ?'),
                optional=False,
                defaultValue=True
            )
        densify.setFlags(densify.flags() | QgsProcessingParameterDefinition.FlagAdvanced)
        self.addParameter(densify)

        sample = QgsProcessingParameterNumber(
            self.SAMPLE,
            self.tr('Sample :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=None,
            optional=False
        )
        self.addParameter(sample)

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Smoothed Gaussian')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import smooth_gaussian
        from cartagen4qgis.src.tools import list_to_qgis_feature_2
        from shapely import Polygon
        from shapely.wkt import loads

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        
        # retrieve the other parameters values
        sigma = self.parameterAsDouble(parameters, self.SIGMA, context)
        sample = self.parameterAsDouble(parameters, self.SAMPLE, context)
        densify = self.parameterAsBoolean(parameters, self.DENSIFY, context)

        #Using CartAGen algorithm and transforming the result to a list of QgsFeature()
        #Depending on the type of geometry of the input data
        
        gs = gdf.copy()
 
        if sample == 0:
            for i in range(len(gdf)):
                gs.loc[i,'geometry'] = smooth_gaussian(list(gs.geometry)[i], sigma=sigma, densify=densify)
                feedback.setProgress(int(i* total))
        else:
            for i in range(len(gdf)):
                gs.loc[i,'geometry'] = smooth_gaussian(list(gs.geometry)[i], sigma=sigma, sample=sample, densify=densify)
                feedback.setProgress(int(i* total))

        res = gs.to_dict('records')
        res = list_to_qgis_feature_2(res,source.fields())

        # Create the output sink    
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, res[0].fields(), source.wkbType(), source.sourceCrs())
        
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        return {
            self.OUTPUT: dest_id
        }
    
class SmoothPlatre (QgsProcessingAlgorithm):
    """  
    Smooth a line and preserve the integrity of sharp turns.

    The PLATRE algorithm was created by Emmanuel Fritsch to attenuate minor bends in a polyline while preserving the position and integrity of the sharpest turns. Unlike simple coordinate-based filters, it operates on the line’s intrinsic geometry (curvature/angle) to maintain structural consistency.

    Parameters:

            geometry (LineString or MultiLineString) – The geometry to smooth.

            sigma (float, optional) – Strength of the smoothing.

            curvature (float, optional) – The curvature threshold to identify sharpest turns. Low values is closer to the original line.

    Returns:

        LineString, MultiLineString
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    SIGMA='SIGMA'
    CURVATURE='CURVATURE'

            
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth Platre'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth lines and patches'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[3]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        helpstring = """
            <b>/!\Doesn't work with multipart geometry/!\</b>
            <b>/!\You need to drop Z and M for the algorithm to function/!\</b>

            Smooth a line and preserve the integrity of sharp turns.
            The PLATRE algorithm was created by Emmanuel Fritsch to attenuate minor bends in a polyline while preserving the position and integrity of the sharpest turns. Unlike simple coordinate-based filters, it operates on the line’s intrinsic geometry (curvature/angle) to maintain structural consistency.
            
            <h3> Parameters: </h3>
            <ul>
                <li> - <em>Sigma </em> :  Strength of the smoothing. </li>
                <li> - <em>Curvature </em> :  The curvature threshold to identify sharpest turns. Low values is closer to the original line. </li>
            </ul>

            For more see <a href="https://cartagen.readthedocs.io/en/latest/reference/cartagen.smooth_platre.html#cartagen.smooth_platre">help online</a>.
        """
        
        return self.tr(helpstring)
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return SmoothPlatre()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        input = QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('The line to smooth :'),
                [QgsProcessing.TypeVectorLine]
            )
        self.addParameter(input)

        sigma = QgsProcessingParameterNumber(
            self.SIGMA,
            self.tr('Sigma :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=30.0,
            optional=False
        )
        self.addParameter(sigma)
    
        curvature = QgsProcessingParameterNumber(
            self.CURVATURE,
            self.tr('Curvature :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=30.0,
            optional=False
        )
        self.addParameter(curvature)

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).   
        output = QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Smoothed Platre'))
        self.addParameter(output)

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import smooth_platre
        from cartagen4qgis.src.tools import list_to_qgis_feature_2

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())
        
        # retrieve the other parameters values
        sigma = self.parameterAsDouble(parameters, self.SIGMA, context)
        curvature = self.parameterAsDouble(parameters, self.CURVATURE, context)
            
        #Using CartAGen algorithm and transforming the result to a list of QgsFeature()
        #Depending on the type of geometry of the input data
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0

        dp = gdf.copy()
        for i in range(len(gdf)):
            dp.loc[i,'geometry'] = smooth_platre(list(gdf.geometry)[i], sigma=sigma,curvature=curvature)
            # Update the progress bar
            feedback.setProgress(int(i * total))
        res = dp.to_dict('records')
        res = list_to_qgis_feature_2(res,source.fields())

        # Create the output sink    
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, res[0].fields(), source.wkbType(), source.sourceCrs())
        
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)
        
        return {
            self.OUTPUT: dest_id
            }
    
class SmoothSnake (QgsProcessingAlgorithm):
    """
    Smooth a line or polygon using the snake method.

    This algorithm proposed by Burghardt treats the geometry as an elastic snake optimizing an energy functional. Internal energy terms (alpha and beta) control the tension and rigidity of the line to smooth out sharp noise, while an external spring force (kappa) anchors the vertices to their original positions to prevent geometric shrinkage and uncontrolled displacement (Burghardt’s shape-preservation term).

    The smoothed position is obtained by solving the linear system
    (𝐴+(𝛾+𝜅)⁢𝐼)⁢𝐱∗=𝛾𝐱0+𝜅𝐱0

    Because both the system matrix and the right-hand side are constant across iterations, the snake converges to the same fixed point regardless of the number of iterations. The iterations parameter therefore controls a pseudo-temporal relaxation: starting from x_0, the snake is advanced iterations steps of implicit Euler integration, which can be useful to observe intermediate states or to limit over-smoothing on short geometries. With iterations=1 the result is the direct closed-form solution.

    Multi-geometries are handled recursively. For polygons, the smoothing is applied independently to the exterior ring and to each interior ring (hole).

    Parameters:

            geometry (LineString, MultiLineString, Polygon, MultiPolygon, LinearRing) – The geometry to smooth. If an open line is provided, the endpoints are preserved. If a closed ring or polygon is provided, the smoothing wraps around.

            iterations (int, optional) – Number of implicit Euler steps for the snake evolution. With iterations=1 the direct closed-form solution is returned. Default is 10.

            alpha (float, optional) – Tension parameter (continuity). Higher values penalise line stretching and pull vertices toward their neighbours. Default is 0.1.

            beta (float, optional) – Rigidity parameter (curvature). Higher values penalise sharp turns and produce smoother, more rounded curves. Default is 0.1.

            gamma (float, optional) – Step-size / weighting of the current position in the RHS. Acts as a regularisation weight on the current iterate rather than a physical viscosity coefficient. Higher values slow down the evolution per step. Default is 1.0.

            kappa (float, optional) – Shape-preservation parameter (Burghardt’s external spring force). Higher values pull the snake back to its original shape, preventing shrinkage and structural collapse. Setting kappa=0 disables this term and closed loops will shrink toward their centroid over many iterations. Default is 0.1.

    Returns:

        LineString, Polygon, MultiLineString, MultiPolygon, LinearRing Smoothed geometry of the same type as the input.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    ITERATIONS='ITERATIONS'
    ALPHA='ALPHA'
    BETA='BETA'
    GAMMA='GAMMA'
    KAPPA='KAPPA'

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth Snake'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth lines and patches'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[0]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        helpstring = """
        Smooth a line or polygon using the snake method.
        This algorithm proposed by Burghardt treats the geometry as an elastic snake optimizing an energy functional. Internal energy terms (alpha and beta) control the tension and rigidity of the line to smooth out sharp noise, while an external spring force (kappa) anchors the vertices to their original positions to prevent geometric shrinkage and uncontrolled displacement (Burghardt’s shape-preservation term). The smoothed position is obtained by solving the linear system (𝐴+(𝛾+𝜅)⁢𝐼)⁢𝐱∗=𝛾𝐱0+𝜅𝐱0 Because both the system matrix and the right-hand side are constant across iterations, the snake converges to the same fixed point regardless of the number of iterations. The iterations parameter therefore controls a pseudo-temporal relaxation: starting from x_0, the snake is advanced iterations steps of implicit Euler integration, which can be useful to observe intermediate states or to limit over-smoothing on short geometries. With iterations=1 the result is the direct closed-form solution. Multi-geometries are handled recursively. For polygons, the smoothing is applied independently to the exterior ring and to each interior ring (hole).
        <h3> Parameters: </h3>
        <ul>
            <li> - <em>Iterations </em> :  Number of implicit Euler steps for the snake evolution. With iterations=1 the direct closed-form solution is returned. Default is 10. </li>
            <li> - <em>Alpha </em> :  Tension parameter (continuity). Higher values penalise line stretching and pull vertices toward their neighbours. Default is 0.1. </li>
            <li> - <em>Beta </em> :  Rigidity parameter (curvature). Higher values penalise sharp turns and produce smoother, more rounded curves. Default is 0.1. </li>
            <li> - <em>Gamma </em> :  Step-size / weighting of the current position in the RHS. Acts as a regularisation weight on the current iterate rather than a physical viscosity coefficient. Higher values slow down the evolution per step. Default is 1.0. </li>
            <li> - <em>Kappa </em> :  Shape-preservation parameter (Burghardt’s external spring force). Higher values pull the snake back to its original shape, preventing shrinkage and structural collapse. Setting kappa=0 disables this term and closed loops will shrink toward their centroid over many iterations. Default is 0.1. </li>
        </ul>

        <b> If an open line is provided, the endpoints are preserved. If a closed ring or polygon is provided, the smoothing wraps around. </b>
        
        For more see <a href="https://cartagen.readthedocs.io/en/latest/reference/cartagen.smooth_snake.html#cartagen.smooth_snake">help online</a>.
        """
        
        return self.tr(helpstring)
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return SmoothSnake()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        input = QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr(' The geometry to smooth :'),
                [QgsProcessing.TypeVectorLine,QgsProcessing.TypeVectorPolygon]
            )
        self.addParameter(input)
    
        iterations = QgsProcessingParameterNumber(
            self.ITERATIONS,
            self.tr('Iterations :'),
            type=QgsProcessingParameterNumber.Integer,
            defaultValue=10.0,
            optional=False
        )
        self.addParameter(iterations)
        
        alpha = QgsProcessingParameterNumber(
            self.ALPHA,
            self.tr('Alpha :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=0.1,
            optional=False
        )
        alpha.setFlags(alpha.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(alpha)
    
        beta = QgsProcessingParameterNumber(
            self.BETA,
            self.tr('Beta :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=0.1,
            optional=False
        )
        beta.setFlags(beta.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(beta)
    
        gamma = QgsProcessingParameterNumber(
            self.GAMMA,
            self.tr('Gamma :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=1.0,
            optional=False
        )
        gamma.setFlags(gamma.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(gamma)
    
        kappa = QgsProcessingParameterNumber(
            self.KAPPA,
            self.tr('Kappa :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=0.1,
            optional=False
        )
        kappa.setFlags(kappa.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(kappa)
        

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).   
        output = QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Smoothed Snake'))
        self.addParameter(output)

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import smooth_snake
        from cartagen4qgis.src.tools import list_to_qgis_feature_2

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())
        
        # retrieve the other parameters values
        iterations = self.parameterAsInt(parameters, self.ITERATIONS, context)
        alpha = self.parameterAsDouble(parameters, self.ALPHA, context)
        beta = self.parameterAsDouble(parameters, self.BETA, context)
        gamma = self.parameterAsDouble(parameters, self.GAMMA, context)
        kappa = self.parameterAsDouble(parameters, self.KAPPA, context)
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        dp = gdf.copy()
        for i in range(len(gdf)):
            dp.loc[i,'geometry'] = smooth_snake (list(gdf.geometry)[i], iterations=iterations,alpha=alpha,beta=beta,gamma=gamma,kappa=kappa)

            # Update the progress bar
            feedback.setProgress(int(i * total))

        res = dp.to_dict('records')
        res = list_to_qgis_feature_2(res,source.fields())

        # Create the output sink    
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, res[0].fields(), source.wkbType(), source.sourceCrs())
        
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)
        
        return {
            self.OUTPUT: dest_id
            }
    
class SmoothTaubin (QgsProcessingAlgorithm):
    """  
    Smooth a line or polygon and prevent shrinkage.

    This algorithm was proposed by Taubin. It is a two-step low-pass filter that preserves volume and prevents shrinkage. It applies alternating expansion and contraction steps using lambda (smoothing) and mu (inflation) parameters.

    Accept Multi geometries. If a polygon is provided, it also applies the smoothing to its holes using the same parameters.

    This implementation is a translation of the C++ implementation available here.

    Parameters:

            geometry (LineString, MultiLineString, Polygon, MultiPolygon, LinearRing) – The line or polygon to smooth. If a line is provided, the first and last vertices are kept fixed. If a closed ring or polygon is provided, all vertices are smoothed.

            iterations (int, optional) – Number of smoothing iterations. Default is 10. More iterations result in stronger smoothing.

            smoothing (float, optional) – Smoothing factor for the first pass. Default is 0.5. Should be positive and typically between 0 and 1.

            inflation (float, optional) – Inflation factor for the second pass. Default is -0.53. Should be negative with inflation slightly larger than smoothing to prevent shrinkage.

    Returns:

        LineString, Polygon, MultiLineString, MultiPolygon, LinearRing  Smoothed geometry of the same type as input.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    ITERATIONS='ITERATIONS'
    SMOOTHING='SMOOTHING'
    INFLATION='INFLATION'

            
    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth Taubin'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth lines and patches'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[2]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        helpstring = f"""
        <b>/!\Doesn't work with multipart geometry, use QGis tool in beforehand. /!\</b>

        Smooth a line or polygon and prevent shrinkage.
        This algorithm was proposed by Taubin. It is a two-step low-pass filter that preserves volume and prevents shrinkage. It applies alternating expansion and contraction steps using lambda (smoothing) and mu (inflation) parameters. Accept Multi geometries. If a polygon is provided, it also applies the smoothing to its holes using the same parameters. This implementation is a translation of the C++ implementation available here.
        <h3> Parameters: </h3>
        <ul>
            <li> - <em>Iterations </em> :  Number of smoothing iterations. Default is 10. More iterations result in stronger smoothing. </li>
            <li> - <em>Smoothing </em> :  Smoothing factor for the first pass. Default is 0.5. Should be positive and typically between 0 and 1. </li>
            <li> - <em>Inflation </em> :  Inflation factor for the second pass. Default is -0.53. Should be negative with inflation slightly larger than smoothing to prevent shrinkage. </li>
        </ul>

        <b>If a line is provided, the first and last vertices are kept fixed. If a closed ring or polygon is provided, all vertices are smoothed.</b>

        For more see <a href="https://cartagen.readthedocs.io/en/latest/reference/cartagen.smooth_taubin.html#cartagen.smooth_taubin">help online</a>.
            
        """
        
        return self.tr(helpstring)
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return SmoothTaubin()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
             
        # We add the input vector features source.
        input = QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('The line or polygon to smooth :'),
                [QgsProcessing.TypeVectorLine,QgsProcessing.TypeVectorPolygon]
            )
        self.addParameter(input)
    
        iterations = QgsProcessingParameterNumber(
            self.ITERATIONS,
            self.tr('Iterations :'),
            type=QgsProcessingParameterNumber.Integer,
            defaultValue=10.0,
            optional=False
        )
        self.addParameter(iterations)
        
        smoothing = QgsProcessingParameterNumber(
            self.SMOOTHING,
            self.tr('Smoothing :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=0.5,
            optional=False
        )
        smoothing.setFlags(smoothing.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(smoothing)

    
        inflation = QgsProcessingParameterNumber(
            self.INFLATION,
            self.tr('Inflation :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=0.53,
            optional=False
        )
        inflation.setFlags(inflation.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(inflation)
        

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).   
        output = QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Smoothed Taubin'))
        self.addParameter(output)

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import smooth_taubin
        from cartagen4qgis.src.tools import list_to_qgis_feature_2

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())
        
        # retrieve the other parameters values
        iterations = self.parameterAsInt(parameters, self.ITERATIONS, context)
        smoothing = self.parameterAsDouble(parameters, self.SMOOTHING, context)
        inflation = self.parameterAsDouble(parameters, self.INFLATION, context)
            
        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        dp = gdf.copy()
        for i in range(len(gdf)):
            dp.loc[i,'geometry'] = smooth_taubin (list(gdf.geometry)[i], iterations=iterations, smoothing=smoothing, inflation=inflation)

            # Update the progress bar
            feedback.setProgress(int(i * total))

        res = dp.to_dict('records')
        res = list_to_qgis_feature_2(res,source.fields())

        # Create the output sink    
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, res[0].fields(), source.wkbType(), source.sourceCrs())
        
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)
        
        return {
            self.OUTPUT: dest_id
            }
    
class SmoothTopographic (QgsProcessingAlgorithm):
    """
    Smooth a line or polygon and mimic hand-made cartographic generalization.

    This algorithm described in Müller and Wang combines both a low-pass filter using weighted moving average (WMA), and a high-pass filter using an angular threshold. It is suitable to smooth topographic features such as rivers, coastlines, lakes, etc. and simplify it to mimic hand-made generalization.

    Accept Multi geometries. If a polygon is provided, it also applies the smoothing to its holes using the same parameters.

    Parameters:

            geometry (LineString, MultiLineString, Polygon, MultiPolygon, LinearRing) – The geometry to smooth. If an open line is provided, the endpoints are preserved. If a closed ring or polygon is provided, the smoothing wraps around.

            iterations (int, optional) – Number of low-pass filter passes before thinning. Default is 2.

            angle (float, optional) – Turning-angle threshold in degrees for the high-pass step. Default is 10.0.

            weights (sequence of odd length, optional) – Weights for the moving average window. Default is [1, 2, 1].

    Returns:

        LineString, MultiLineString, Polygon, MultiPolygon, LinearRing Simplified geometry of the same type as input.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    ITERATIONS='ITERATIONS'
    ANGLE='ANGLE'
    WEIGHT1='WEIGHT1'
    WEIGHT2='WEIGHT2'
    WEIGHT3='WEIGHT3'

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth Topographic'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth lines and patches'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[0]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        helpstring = """
        Smooth a line or polygon and mimic hand-made cartographic generalization.
        This algorithm described in Müller and Wang combines both a low-pass filter using weighted moving average (WMA), and a high-pass filter using an angular threshold. It is suitable to smooth topographic features such as rivers, coastlines, lakes, etc. and simplify it to mimic hand-made generalization. Accept Multi geometries. If a polygon is provided, it also applies the smoothing to its holes using the same parameters.
        <h3> Parameters: </h3>
        <ul>
            <li> - <em>Iterations </em> :  Number of low-pass filter passes before thinning. Default is 2. </li>
            <li> - <em>Angle </em> :  Turning-angle threshold in degrees for the high-pass step. Default is 10.0. </li>
            <li> - <em>Weights </em> :  Weights for the moving average window. Default is [1, 2, 1]. </li>
        </ul>
        For more see <a href="https://cartagen.readthedocs.io/en/latest/reference/cartagen.smooth_topographic.html#cartagen.smooth_topographic">help online</a>.
        """
        
        return self.tr(helpstring)
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return SmoothTopographic()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        input = QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('The geometry to smooth :'),
                [QgsProcessing.TypeVectorLine,QgsProcessing.TypeVectorPolygon]
            )
        self.addParameter(input)
    
        iterations = QgsProcessingParameterNumber(
            self.ITERATIONS,
            self.tr('Iterations :'),
            type=QgsProcessingParameterNumber.Integer,
            defaultValue=2,
            optional=False
        )
        self.addParameter(iterations)
        
        angle = QgsProcessingParameterNumber(
            self.ANGLE,
            self.tr('Angle :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=10.0,
            optional=False
        )
        angle.setFlags(angle.flags() | QgsProcessingParameterDefinition.FlagAdvanced)
        self.addParameter(angle)

        weight1 = QgsProcessingParameterNumber(
            name=self.WEIGHT1,
            description="Weight 1:",
            defaultValue =1,
            type=QgsProcessingParameterNumber.Double,
        )
        weight1.setFlags(weight1.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(weight1)

        weight2 = QgsProcessingParameterNumber(
            name=self.WEIGHT2,
            description="Weight 2:",
            defaultValue=2,
            type=QgsProcessingParameterNumber.Double,
        )
        weight2.setFlags(weight2.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(weight2)

        weight3 = QgsProcessingParameterNumber(
            name=self.WEIGHT3,
            description="Weight 3:",
            defaultValue=1,
            type=QgsProcessingParameterNumber.Double,
        )
        weight3.setFlags(weight3.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(weight3)    
            
        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).   
        output = QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Smoothed Topographic'))
        self.addParameter(output)

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import smooth_topographic
        from cartagen4qgis.src.tools import list_to_qgis_feature_2

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())
        
        # retrieve the other parameters values
        iterations = self.parameterAsInt(parameters, self.ITERATIONS, context)
        angle = self.parameterAsDouble(parameters, self.ANGLE, context)
        weight1 = self.parameterAsDouble(parameters, self.WEIGHT1, context)
        weight2 = self.parameterAsDouble(parameters, self.WEIGHT2, context)
        weight3 = self.parameterAsDouble(parameters, self.WEIGHT3, context)
            
        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        dp = gdf.copy()
        for i in range(len(gdf)):
            dp.loc[i,'geometry'] = smooth_topographic (list(gdf.geometry)[i], iterations=iterations,angle=angle,weights=[weight1,weight2,weight3])

            # Update the progress bar
            feedback.setProgress(int(i * total))

        res = dp.to_dict('records')
        res = list_to_qgis_feature_2(res,source.fields())

        # Create the output sink    
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, res[0].fields(), source.wkbType(), source.sourceCrs())
        
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)
        
        return {
            self.OUTPUT: dest_id
            }
    
class SmoothWMA (QgsProcessingAlgorithm):
    """
    Smooth a line or polygon using a low-pass filter.

    This algorithm described in McMaster for a generalization purpose applies a weighted moving average (WMA) window over the vertices. The default weights [1, 2, 1] heavily weight the central point to suppress unwanted short-wavelength noise while minimizing overall geometric shrinkage.

    Accept Multi geometries. If a polygon is provided, it also applies the smoothing to its holes using the same parameters.

    Parameters:

            geometry (LineString, MultiLineString, Polygon, MultiPolygon, LinearRing) – The geometry to smooth. If an open line is provided, the endpoints are preserved. If a closed ring or polygon is provided, the smoothing wraps around.

            iterations (int, optional) – Number of iterations to apply the filter. Default is 1.

            weights (sequence of odd length, optional) – Weights for the moving average window. Default is [1, 2, 1].

    Returns:

        LineString, Polygon, MultiLineString, MultiPolygon, LinearRing Smoothed geometry of the same type as input.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    ITERATIONS='ITERATIONS'
    WEIGHT1='WEIGHT1'
    WEIGHT2='WEIGHT2'
    WEIGHT3='WEIGHT3'

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth WMA'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Smooth lines and patches'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[0]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        helpstring = """
        Smooth a line or polygon using a low-pass filter.
        This algorithm described in McMaster for a generalization purpose applies a weighted moving average (WMA) window over the vertices. The default weights [1, 2, 1] heavily weight the central point to suppress unwanted short-wavelength noise while minimizing overall geometric shrinkage. Accept Multi geometries. If a polygon is provided, it also applies the smoothing to its holes using the same parameters.
        <h3> Parameters: </h3>
        <ul>
          <li> - <em>Iterations </em> :  Number of iterations to apply the filter. Default is 1. </li>
          <li> - <em>Weights </em> :  Weights for the moving average window. Default is [1, 2, 1]. </li>
        </ul>
        For more see <a href="https://cartagen.readthedocs.io/en/latest/reference/cartagen.smooth_wma.html#cartagen.smooth_wma">help online</a>.
        """
        
        return self.tr(helpstring)
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return SmoothWMA()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        input = QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr(' The geometry to smooth. If an open line is provided, the endpoints are preserved. If a closed ring or polygon is provided, the smoothing wraps around. :'),
                [QgsProcessing.TypeVectorLine,QgsProcessing.TypeVectorPolygon]
            )
        self.addParameter(input)
    
        iterations = QgsProcessingParameterNumber(
            self.ITERATIONS,
            self.tr('Iterations :'),
            type=QgsProcessingParameterNumber.Integer,
            defaultValue=1,
            optional=False
        )
        self.addParameter(iterations)
        
        weight1 = QgsProcessingParameterNumber(
            name=self.WEIGHT1,
            description="Weight 1:",
            defaultValue =1,
            type=QgsProcessingParameterNumber.Double,
        )
        weight1.setFlags(weight1.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(weight1)

        weight2 = QgsProcessingParameterNumber(
            name=self.WEIGHT2,
            description="Weight 2:",
            defaultValue=2,
            type=QgsProcessingParameterNumber.Double,
        )
        weight2.setFlags(weight2.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(weight2)

        weight3 = QgsProcessingParameterNumber(
            name=self.WEIGHT3,
            description="Weight 3:",
            defaultValue=1,
            type=QgsProcessingParameterNumber.Double,
        )
        weight3.setFlags(weight3.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(weight3)
            
        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).   
        output = QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Smoothed Wma'))
        self.addParameter(output)

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import smooth_wma
        from cartagen4qgis.src.tools import list_to_qgis_feature_2

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())
        
        # retrieve the other parameters values

        iterations = self.parameterAsInt(parameters, self.ITERATIONS, context)
        weight1 = self.parameterAsDouble(parameters, self.WEIGHT1, context)
        weight2 = self.parameterAsDouble(parameters, self.WEIGHT2, context)
        weight3 = self.parameterAsDouble(parameters, self.WEIGHT3, context)            
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        dp = gdf.copy()
        for i in range(len(gdf)):
            dp.loc[i,'geometry'] = smooth_wma (list(gdf.geometry)[i], iterations=iterations,weights=[weight1, weight2, weight3])

            # Update the progress bar
            feedback.setProgress(int(i * total))

        res = dp.to_dict('records')
        res = list_to_qgis_feature_2(res,source.fields())

        # Create the output sink    
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, res[0].fields(), source.wkbType(), source.sourceCrs())
        
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)
        
        return {
            self.OUTPUT: dest_id
            }