# -*- coding: utf-8 -*-
"""
/***************************************************************************
CartAGen4QGIS
A QGIS plugin
Cartographic generalization
Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
-------------------
        begin                : 2023-05-11
        copyright            : (C) 2023 by Guillaume Touya, Justin Berli & Paul Bourcier
        email                : guillaume.touya@ign.fr
 ***************************************************************************/
"""
__author__ = 'Guillaume Touya, Justin Berli & Paul Bourcier'
__date__ = '2023-05-11'
__copyright__ = '(C) 2023 by Guillaume Touya, Justin Berli & Paul Bourcier'
# This will get replaced with a git SHA1 when you do a git archive
__revision__ = '$Format:%H$'

import os
import sys
import subprocess
import inspect

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class CartAGen4QGISPlugin(object):
    
    def __init__(self):
        self.provider = None
        self.plugin_dir = os.path.dirname(__file__)
        self.initialized = False
    
    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        if self.initialized:
            return  # Éviter la double initialisation
            
        try:
            # Import retardé pour éviter les problèmes de chargement
            from qgis.core import QgsApplication
            from cartagen4qgis.src.provider import CartAGen4QGISProvider
            self.provider = CartAGen4QGISProvider()
            QgsApplication.processingRegistry().addProvider(self.provider)
            self.initialized = True
        except Exception as e:
            from qgis.core import QgsMessageLog, Qgis
            QgsMessageLog.logMessage(
                f"There was an error during the initialization of the Processing provider: {str(e)}",
                'CartAGen',
                Qgis.Critical
            )
    
    def initGui(self):
        # Delay qt modules import
        try:
            from qgis.core import QgsMessageLog, Qgis

            # Check dependencies
            if not self.check_dependencies():
                if self.is_flatpak():
                    self.show_flatpak_instructions()
                else:
                    self.prompt_install_dependencies()

            if not self.initialized:
                self.initProcessing()
                    
        except Exception as e:
            # Use a try catch to avoid QGIS crashing
            try:
                from qgis.core import QgsMessageLog, Qgis
                QgsMessageLog.logMessage(
                    f"There was an error while loading the CartAGen plugin: {str(e)}",
                    'CartAGen',
                    Qgis.Critical
                )
            except:
                # If logging fail, send to stderr
                print(f"CRITICAL ERROR WITH CARTAGEN4QGIS PLUGIN: {str(e)}", file=sys.stderr)
    
    def unload(self):
        try:
            from qgis.core import QgsApplication
            if self.provider and self.initialized:
                QgsApplication.processingRegistry().removeProvider(self.provider)
                self.provider = None
                self.initialized = False
        except Exception as e:
            # Ignorer les erreurs au déchargement
            QgsMessageLog.logMessage(
                    "Unable to unload CartAGen plugin. Try restart QGIS.",
                    'CartAGen',
                    Qgis.Critical
                )
    
    # ========== GESTION DES DÉPENDANCES ==========
    
    def is_flatpak(self):
        """Check if QGIS is runnning within a flatpak environment"""
        return os.path.exists('/.flatpak-info') or \
            'flatpak' in sys.executable.lower() or \
            '/app/' in sys.prefix
    
    def check_dependencies(self):
        """Check if cartagen have been installed already"""
        try:
            __import__('cartagen')
        except ImportError:
            return False
        return True
    
    def prompt_install_dependencies(self):
        """Display a prompt to ask for the installation of cartagen"""
        try:
            from qgis.PyQt.QtWidgets import QMessageBox
            from qgis.core import Qgis
            
            if str(Qgis.QGIS_VERSION_INT)[0] == '4':
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Icon.Information)
                msgBox.setText("""CartAGen won't work without the proper dependencies.<br>
                                         You must manually install the CartAGen Python library.<br>
                                         Tutorial is available on our <a href="https://cartagen.readthedocs.io/en/latest/qgis.html">documentation page</a> !""")
                msgBox.setWindowTitle("Missing CartAGen library")
                msgBox.setStandardButtons(QMessageBox.StandardButton.Ok)
                msgBox.exec()
                
            elif str(Qgis.QGIS_VERSION_INT)[0] == '3':
                msgBox = QMessageBox()
                msgBox.setIcon(QMessageBox.Information)
                msgBox.setText("""CartAGen won't work without the proper dependencies.<br>
                                         You must manually install the CartAGen Python library.<br>
                                         Tutorial is available on our <a href="https://cartagen.readthedocs.io/en/latest/qgis.html">documentation page</a> !""")
                msgBox.setWindowTitle("Missing CartAGen library")
                msgBox.setStandardButtons(QMessageBox.Ok)
                msgBox.exec()
      
        except Exception as e:
            from qgis.core import QgsMessageLog, Qgis
            QgsMessageLog.logMessage(
                f"There was an error during the dialog display: {str(e)}",
                'CartAGen',
                Qgis.Critical
            )
    
    def show_flatpak_instructions(self):
        """Display Flatpak information"""
        try:
            from qgis.PyQt.QtWidgets import QDialog, QVBoxLayout, QTextBrowser, QPushButton, QMessageBox, QApplication
            
            dialog = QDialog()
            dialog.setWindowTitle("Missing dependencies for the CartAGen plugin")
            dialog.setMinimumWidth(650)
            dialog.setMinimumHeight(500)
            
            layout = QVBoxLayout()
            
            text_browser = QTextBrowser()
            text_browser.setOpenExternalLinks(True)
            text_browser.setHtml("""
                <h2>Detected QGIS installed with Flatpak - Dependencies required for CartAGen plugin</h2>
                
                <p>CartAGen needs some Python dependencies to properly work. You need
                to install them within the Python environment used by QGIS.</p>
                
                <h3>Instructions :</h3>
                
                <ol>
                    <li><b>Close QGIS</b></li>
                    <li>Open a terminal</li>
                    <li>Execute the following commands:</li>
                </ol>
                
                <pre style="background-color: #f5f5f5; padding: 10px; border-radius: 5px; font-family: monospace;">
flatpak run --devel --command=pip3 org.qgis.qgis install cartagen
                </pre>
                
                <p><b>Note :</b> If you get an error with <code>--devel</code>, 
                you should first install the SDK (replace VERSION with the version returned in the error):</p>
                
                <pre style="background-color: #f5f5f5; padding: 10px; border-radius: 5px; font-family: monospace;">
flatpak install org.kde.Sdk/x86_64/VERSION
                </pre>
                
                <p>Once installed, restart QGIS.</p>
                
                <p>More information on the CartAGen documentation page: 
                <a href="https://cartagen.readthedocs.io/en/latest/qgis.html">Documentation CartAGen</a></p>
            """)
            
            layout.addWidget(text_browser)
            
            # Button to copy command
            copy_button = QPushButton("Copy the installation command")
            copy_button.clicked.connect(lambda: self.copy_flatpak_commands())
            layout.addWidget(copy_button)
            
            close_button = QPushButton("Close")
            close_button.clicked.connect(dialog.close)
            layout.addWidget(close_button)
            
            dialog.setLayout(layout)
            dialog.exec()
        except Exception as e:
            from qgis.core import QgsMessageLog, Qgis
            QgsMessageLog.logMessage(
                f"Error during the display of Flatpak instructions: {str(e)}",
                'CartAGen',
                Qgis.Critical
            )
    
    def copy_flatpak_commands(self):
        """Copy flatpak commands in the clipboard"""
        try:
            from qgis.PyQt.QtWidgets import QMessageBox, QApplication
            commands = """flatpak run --devel --command=pip3 org.qgis.qgis install cartagen"""
            QApplication.clipboard().setText(commands)
            QMessageBox.information(
                None,
                "Copied",
                "The Flatpak installation command was copied in your clipboard.\n"
                "Paste them inside a terminal using Ctrl+Shift+V"
            )
        except Exception as e:
            from qgis.core import QgsMessageLog, Qgis
            QgsMessageLog.logMessage(
                f"Error during flatpak command copying: {str(e)}",
                'CartAGen',
                Qgis.Critical
            )
