# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CartAGen4QGIS
                                 A QGIS plugin
 Cartographic generalization
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-06-18
        copyright            : (C) 2024 by Guillaume Touya, Justin Berli & Paul Bourcier
        email                : guillaume.touya@ign.fr
 ***************************************************************************/
"""

__author__ = 'Guillaume Touya, Justin Berli & Paul Bourcier'
__date__ = '2024-06-18'
__copyright__ = '(C) 2024 by Guillaume Touya, Justin Berli & Paul Bourcier'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import QgsProcessingAlgorithm

class SkelNatural(QgsProcessingAlgorithm):
    
    """
    Create the natural TIN skeleton of a polygon.

    The natural skeleton means the entry points of the skeleton are naturally calculated during the skeleton creation, it depends on the Delaunay triangulation.

    This version is inspired by the enhanced TIN skeleton proposed by Wang.

    Parameters:

        Polygon (Polygon) – The polygon to compute the skeleton from.

        Threshold_range (tuple, optional) – This value is only used for inner triangles calculated by the Delaunay triangulation. If two of the length ratio between each pair of edges (of an inner triangle) is outside the given range, the skeleton uses the middle of the line connecting the two center of the longest lines of the triangle, else it uses the centroid of the triangle

    Returns:

        list of LineString
    """

    INPUT='INPUT'
    OUTPUT='OUTPUT'
    LOW_BOUND='LOW_BOUND'
    UP_BOUND='UP_BOUND'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    
    def name(self):

        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """

        return "Skeletonize Natural"

    def displayName(self):
        
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """

        return self.tr(self.name())
    
    def groupId(self):

        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """

        return "Skeletonize and Spinalize polygons"
    
    def group(self):
        
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """

        return self.tr(self.groupId())
    
    def icon(self):
        
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """

        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[3]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):

        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """

        helpstring = self.tr("""
            <b>/!\ If you don't drop Z and M, it won't work ! /!\</b>
            <b>/!\ Don't work with multi-part geometry /!\</b>
                             
            Create the natural TIN skeleton of a polygon.
            The natural skeleton means the entry points of the skeleton are naturally calculated during the skeleton creation, it depends on the Delaunay triangulation.
            This version is inspired by the enhanced TIN skeleton proposed by Wang.
            
            <h3> Parameters: </h3>
            <ul>
                <li> - <em>Threshold range</em> : This value is only used for inner triangles calculated by the Delaunay triangulation. If two of the length ratio between each pair of edges (of an inner triangle) is outside the given range, the skeleton uses the middle of the line connecting the two center of the longest lines of the triangle, else it uses the centroid of the triangle</li>
            </ul>
            
            For more see <a href="https://cartagen.readthedocs.io/en/latest/reference/cartagen.skeletonize_natural.html#cartagen.skeletonize_natural">help online</a>.
        """)

        return helpstring
    

    def createInstance(self):
        return SkelNatural()

    def initAlgorithm(self, config):

        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        from qgis.core import (
            QgsProcessing,
            QgsProcessingParameterDefinition,
            QgsProcessingParameterNumber,
            QgsProcessingParameterFeatureSink,
            QgsProcessingParameterFeatureSource
        )

        input = QgsProcessingParameterFeatureSource(
            name=self.INPUT,
            description="The polygon to compute the skeleton from :",
            types=[QgsProcessing.TypeVectorPolygon]
        )
        self.addParameter(input)

        low_bound = QgsProcessingParameterNumber(
            name=self.LOW_BOUND,
            description="Lower bound of a the threshold range :",
            type=QgsProcessingParameterNumber.Double,
            defaultValue=0.7
        )
        low_bound.setFlags(low_bound.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(low_bound)

        up_bound = QgsProcessingParameterNumber(
            name=self.UP_BOUND,
            description="Upper bound of a the threshold range :",
            type=QgsProcessingParameterNumber.Double,
            defaultValue=1.4
        )
        up_bound.setFlags(up_bound.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(up_bound)

        output = QgsProcessingParameterFeatureSink(
            name=self.OUTPUT,
            description="Skeletonized Natural"
        )
        self.addParameter(output)

    def processAlgorithm(self, parameters, context, feedback):

        """
        Here is where the processing itself takes place.
        """

        from cartagen4qgis.src.tools import list_to_qgis_feature_2
        from cartagen import skeletonize_natural
        import geopandas as gpd
        from qgis.core import (QgsFeatureSink, QgsWkbTypes)

        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())

        low_bound = self.parameterAsDouble(parameters, self.LOW_BOUND, context)
        up_bound = self.parameterAsDouble(parameters, self.UP_BOUND, context)

        gs = gdf.copy()
        gs = gs.drop(columns=['geometry'])

        listSkel = []
        for index in range(len(gs)):
            skeletonized = skeletonize_natural(gdf.loc[index,'geometry'], threshold_range=(low_bound, up_bound))
            listSkel.append(skeletonized[0])

        gs = gs.assign(geometry=listSkel)
        res = gs.to_dict('records')
        res = list_to_qgis_feature_2(res, source.fields())

        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context,
            res[0].fields(), QgsWkbTypes.LineString, source.sourceCrs()
        )

        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        return {
            self.OUTPUT: dest_id
        }

class SkelArtificial(QgsProcessingAlgorithm):
    
    """
    Create a TIN skeleton from a polygon by enforcing entry points.

    The artificial skeleton means the entry points of the skeleton are manually set and the natural entry points of the skeleton calculated during the skeleton creation are removed.

    This version is inspired by the enhanced TIN skeleton proposed by Wang [1]

    Parameters:

            polygon (Polygon) – The polygon to compute the skeleton from.

            entries (list of Point) – The entry points of the skeleton.

            connection (str, optional) – Connection can be ‘joint’, which forces the entry point to connect to the closest joint, or can be ‘interior’, which first look if there is an interior triangle inside the triangulation and connect directly the entry point to its skeleton joint. If no interior triangle is found, apply ‘joint’ connection instead.

            threshold_range (tuple, optional) – This value is only used for inner triangles calculated by the Delaunay triangulation. If two of the length ratio between each pair of edges (of an inner triangle) is outside the given range, the skeleton uses the middle of the line connecting the two center of the longest lines of the triangle, else it uses the centroid of the triangle.

    Returns:

        list of LineString
    """

    INPUT='INPUT'
    OUTPUT='OUTPUT'
    ENTRIES='ENTRIES'
    CONNECTION='CONNECTION'
    LOW_BOUND='LOW_BOUND'
    UP_BOUND='UP_BOUND'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    
    def name(self):

        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """

        return "Skeletonize Artificial"

    def displayName(self):
        
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """

        return self.tr(self.name())
    
    def groupId(self):

        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """

        return "Skeletonize and Spinalize polygons"
    
    def group(self):
        
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """

        return self.tr(self.groupId())
    
    def icon(self):
        
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """

        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[2]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):

        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """

        helpstring = self.tr( """
            <b>/!\ If you don't drop Z and M, it won't work ! /!\</b>
                             
            Create a TIN skeleton from a polygon by enforcing entry points.
            The artificial skeleton means the entry points of the skeleton are manually set and the natural entry points of the skeleton calculated during the skeleton creation are removed.
            This version is inspired by the enhanced TIN skeleton proposed by Wang
                             
            <h3> Parameters: </h3>
                             
            <ul>
                <li> - <em>Entries</em> : The entry points of the skeleton.</li>
                <li> - <em>Connection</em> : It can be :</li>
                    <ul>
                        <li>. <em>'joint'</em>, which forces the entry point to connect to the closest joint</li>
                        <li>. <em>'interior'</em>, which first look if there is an interior triangle inside the triangulation and connect directly the entry point to its skeleton joint. If no interior triangle is found, apply ‘joint’ connection instead.</li>
                    </ul>
                <li> - <em>Threshold range</em> : This value is only used for inner triangles calculated by the Delaunay triangulation. If two of the length ratio between each pair of edges (of an inner triangle) is outside the given range, the skeleton uses the middle of the line connecting the two center of the longest lines of the triangle, else it uses the centroid of the triangle.</li>
            </ul>
                             
            For more see <a href="https://cartagen.readthedocs.io/en/latest/reference/cartagen.skeletonize_artificial.html#cartagen.skeletonize_artificial">help online</a>.
        """)

        return helpstring
    

    def createInstance(self):
        return SkelArtificial()

    def initAlgorithm(self, config):

        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        from qgis.core import (
            QgsProcessing,
            QgsProcessingParameterVectorLayer,
            QgsProcessingParameterEnum,
            QgsProcessingParameterDefinition,
            QgsProcessingParameterNumber,
            QgsProcessingParameterFeatureSink,
            QgsProcessingParameterFeatureSource
        )

        input = QgsProcessingParameterFeatureSource(
            name=self.INPUT,
            description="The polygon to compute the skeleton from :",
            types=[QgsProcessing.TypeVectorPolygon]
        )
        self.addParameter(input)

        entries = QgsProcessingParameterFeatureSource(
            name=self.ENTRIES,
            description="Entries :",
            types=[QgsProcessing.TypeVectorPoint]
        )
        self.addParameter(entries)

        connection = QgsProcessingParameterEnum(
            name=self.CONNECTION,
            description="Connection :",
            options=['joint', 'interior'],
            defaultValue = 'joint'
        )
        connection.setFlags(connection.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(connection)

        low_bound = QgsProcessingParameterNumber(
            name=self.LOW_BOUND,
            description="Lower bound of a the threshold range :",
            type=QgsProcessingParameterNumber.Double,
            defaultValue=0.7
        )
        low_bound.setFlags(low_bound.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(low_bound)

        up_bound = QgsProcessingParameterNumber(
            name=self.UP_BOUND,
            description="Upper bound of a the threshold range :",
            type=QgsProcessingParameterNumber.Double,
            defaultValue=1.4
        )
        up_bound.setFlags(up_bound.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(up_bound)

        output = QgsProcessingParameterFeatureSink(
            name=self.OUTPUT,
            description="Skeletonized Artificial"
        )
        self.addParameter(output)

    def processAlgorithm(self, parameters, context, feedback):

        """
        Here is where the processing itself takes place.
        """

        from cartagen4qgis.src.tools import list_to_qgis_feature_2
        from cartagen import skeletonize_artificial
        import geopandas as gpd
        from qgis.core import (QgsFeatureSink, QgsWkbTypes)
        from shapely import LineString

        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())

        entries = self.parameterAsVectorLayer(parameters, self.ENTRIES, context)
        entries = gpd.GeoDataFrame.from_features(entries.getFeatures())
        entries = list(entries['geometry'])

        connection = self.parameterAsEnum(parameters, self.CONNECTION, context)
        listConnection = ['joint', 'interior']
        low_bound = self.parameterAsDouble(parameters, self.LOW_BOUND, context)
        up_bound = self.parameterAsDouble(parameters, self.UP_BOUND, context)        

        gs = gdf.copy()
        gs = gs.drop(columns=['geometry'])

        listSkel = []
        for index in range(len(gs)):
            skeletonized = skeletonize_artificial(gdf.loc[index,'geometry'], entries=entries, connection=listConnection[connection], threshold_range=(low_bound, up_bound))
            listSkel.append(skeletonized[0])

        gs = gs.assign(geometry=listSkel)

        res = gs.to_dict('records')
        res = list_to_qgis_feature_2(res, source.fields())

        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context,
            res[0].fields(), QgsWkbTypes.LineString, source.sourceCrs()
        )

        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        return {
            self.OUTPUT: dest_id
        }

class SkelNetwork(QgsProcessingAlgorithm):
    
    """
    Create an artificial TIN skeleton and blend it inside a network.

    This function first creates an artificial TIN skeleton by enforcing entry points derived from the provided network (the entry points are the extremities of the provided network touching the polygon ring). Then the network is blended with the skeleton and an optional gaussian smoothing is apply.

    This version is inspired by the enhanced TIN skeleton proposed by Wang [1]

    Parameters:

            polygon (Polygon) – The polygon to compute the skeleton from.

            network (GeoDataFrame of LineString) – The network touching the ring of the polygon.

            sigma (float, optional) – Gaussian filter strength. By default, the skeleton is not smoothed.

            attributes (list of dict, optional) – A list of dict where the index matches the provided network. This dict represents the attributes of the lines to be propagated to the new network. If None is provided, the resulting network will lack the original attributes.

            blend_smoothing (bool, optional) – If set to True, the gaussian smoothing is applied to the skeleton after blending with the rest of the network, this can deform the network outside of the dual carriageways. If set to False, the gaussian smoothing is only applied to the skeleton before blending with the rest of the network.

            threshold_range (tuple, optional) – This value is only used for inner triangles calculated by the Delaunay triangulation. If two of the length ratio between each pair of edges (of an inner triangle) is outside the given range, the skeleton uses the middle of the line connecting the two center of the longest lines of the triangle, else it uses the centroid of the triangle.

    Returns:

        GeoDataFrame of LineString
    """

    INPUT='INPUT'
    OUTPUT='OUTPUT'
    NETWORK='NETWORK'
    SIGMA='SIGMA'
    BLEND_SMOOTHING='BLEND_SMOOTHING'
    LOW_BOUND='LOW_BOUND'
    UP_BOUND='UP_BOUND'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)
    
    def name(self):

        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """

        return "Skeletonize Network"

    def displayName(self):
        
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """

        return self.tr(self.name())
    
    def groupId(self):

        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """

        return "Skeletonize and Spinalize polygons"
    
    def group(self):
        
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """

        return self.tr(self.groupId())
    
    def icon(self):
        
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """

        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[2]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        helpstring = self.tr("""
            <b>/!\ If you don't drop Z and M, it won't work ! /!\</b>
                             
            Create an artificial TIN skeleton and blend it inside a network.
            This function first creates an artificial TIN skeleton by enforcing entry points derived from the provided network (the entry points are the extremities of the provided network touching the polygon ring). Then the network is blended with the skeleton and an optional gaussian smoothing is apply.
            This version is inspired by the enhanced TIN skeleton proposed by Wang
            
            <h3> Parameters: </h3>
            <ul>
                <li> - <em>Network</em> : The network touching the ring of the polygon.</li>
                <li> - <em>Sigma</em> : Gaussian filter strength. By default, the skeleton is not smoothed.</li>
                <li> - <em>Blend smoothing</em> : If set to True, the gaussian smoothing is applied to the skeleton after blending with the rest of the network, this can deform the network outside of the dual carriageways. If set to False, the gaussian smoothing is only applied to the skeleton before blending with the rest of the network.</li>
                <li> - <em>Threshold range</em> : This value is only used for inner triangles calculated by the Delaunay triangulation. If two of the length ratio between each pair of edges (of an inner triangle) is outside the given range, the skeleton uses the middle of the line connecting the two center of the longest lines of the triangle, else it uses the centroid of the triangle.</li>
            </ul>
                             
            For more see <a href="https://cartagen.readthedocs.io/en/latest/reference/cartagen.skeletonize_network.html#cartagen.skeletonize_network">help online</a>.
        """)

        return helpstring
    

    def createInstance(self):
        return SkelNetwork()

    def initAlgorithm(self, config):

        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        from qgis.core import (
            QgsProcessing,
            QgsProcessingParameterVectorLayer,
            QgsProcessingParameterEnum,
            QgsProcessingParameterBoolean,
            QgsProcessingParameterDefinition,
            QgsProcessingParameterNumber,
            QgsProcessingParameterFeatureSink,
            QgsProcessingParameterFeatureSource
        )

        input = QgsProcessingParameterFeatureSource(
            name=self.INPUT,
            description="The polygon to compute the skeleton from :",
            types=[QgsProcessing.TypeVectorPolygon]
        )
        self.addParameter(input)

        network = QgsProcessingParameterFeatureSource(
            name=self.NETWORK,
            description="Network :",
            types=[QgsProcessing.TypeVectorLine]
        )
        self.addParameter(network)

        sigma = QgsProcessingParameterNumber(
            name=self.SIGMA,
            description="Sigma :",
            type=QgsProcessingParameterNumber.Double,
            defaultValue = 0
        )
        sigma.setFlags(sigma.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(sigma)

        blend_smoothing = QgsProcessingParameterBoolean(
            name=self.BLEND_SMOOTHING,
            description="Blend smoothing ?",
            defaultValue = False
        )
        blend_smoothing.setFlags(blend_smoothing.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(blend_smoothing)

        low_bound = QgsProcessingParameterNumber(
            name=self.LOW_BOUND,
            description="Lower bound of a the threshold range :",
            type=QgsProcessingParameterNumber.Double,
            defaultValue=0.7
        )
        low_bound.setFlags(low_bound.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(low_bound)

        up_bound = QgsProcessingParameterNumber(
            name=self.UP_BOUND,
            description="Upper bound of a the threshold range :",
            type=QgsProcessingParameterNumber.Double,
            defaultValue=1.4
        )
        up_bound.setFlags(up_bound.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(up_bound)

        output = QgsProcessingParameterFeatureSink(
            name=self.OUTPUT,
            description="Skeletonized Network"
        )
        self.addParameter(output)

    def processAlgorithm(self, parameters, context, feedback):

        """
        Here is where the processing itself takes place.
        """

        from cartagen4qgis.src.tools import list_to_qgis_feature_2
        from cartagen import skeletonize_network
        import geopandas as gpd
        from qgis.core import (QgsFeatureSink, QgsWkbTypes)

        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())

        network = self.parameterAsVectorLayer(parameters, self.NETWORK, context)
        network = gpd.GeoDataFrame.from_features(network.getFeatures())

        sigma = self.parameterAsDouble(parameters, self.SIGMA, context)
        blend_smoothing = self.parameterAsBoolean(parameters, self.BLEND_SMOOTHING, context)
        low_bound = self.parameterAsDouble(parameters, self.LOW_BOUND, context)
        up_bound = self.parameterAsDouble(parameters, self.UP_BOUND, context)        

        gs = gdf.copy()
        gs = gs.drop(columns=['geometry'])

        listSkel = []
        for index in range(len(gs)):
            skeletonized = skeletonize_network(gdf.loc[index,'geometry'], network=network, sigma=sigma, blend_smoothing=blend_smoothing, threshold_range=(low_bound, up_bound))
            listSkel.append(skeletonized[0])

        gs = gs.assign(geometry=listSkel)
        res = gs.to_dict('records')
        res = list_to_qgis_feature_2(res, source.fields())

        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context,
            res[0].fields(), QgsWkbTypes.LineString, source.sourceCrs()
        )

        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        return {
            self.OUTPUT: dest_id
        }