# -*- coding: utf-8 -*-

"""
/***************************************************************************
 CartAGen4QGIS
                                 A QGIS plugin
 Cartographic generalization
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-05-11
        copyright            : (C) 2023 by Guillaume Touya, Justin Berli & Paul Bourcier
        email                : guillaume.touya@ign.fr
 ***************************************************************************/
"""

__author__ = 'Guillaume Touya, Justin Berli & Paul Bourcier'
__date__ = '2023-05-11'
__copyright__ = '(C) 2023 by Guillaume Touya, Justin Berli & Paul Bourcier'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import QgsProcessing, QgsFeatureSink, QgsProcessingAlgorithm, QgsFeature, QgsGeometry, QgsProcessingParameterDefinition
from qgis.core import (
    QgsProcessingParameterFeatureSource,
    QgsProcessingParameterFeatureSink, 
    QgsProcessingParameterNumber, 
    QgsProcessingParameterString, 
    QgsProcessingParameterBoolean,
    QgsProcessingParameterEnum
)

class SquaringPolygonLS(QgsProcessingAlgorithm):

    """
    Squares a polygon using the method of least squares.

    The least squares based polygon squaring algorithm was proposed by Touya and Lokhat [1] and is particularly useful to square buildings.

    In practice, this function iteratively tries to resolve matrices equations until a threshold norm is reached and the provided constraint are satisfied.

    Parameters:

        polygon (Polygon) – The polygon to square.

        max_iteration (float, optional) – This is the maximum number of iteration before breaking the loop. If constraints and weights are correctly set, the norm tolerance threshold should be reached before the maximum number of iteration.

        norm_tolerance (float, optional) – The threshold below which the norm of the resulting point matrix is acceptable enough to break the iteration loop.

        right_tolerance (float, optional) – Tolerance in degrees to consider an angle to be right.

        flat_tolerance (float, optional) – Tolerance in degrees to consider an angle to be flat.

        fixed_weight (int, optional) – The weight of the angle constraint concerning an angle neither right nor flat. A high value means those angles will be more likely to keep their value in the resulting polygon.

        right_weight (int, optional) – The weight of the angle constraint concerning right angles. A high value means those angles will be more likely to keep their value in the resulting polygon.

        flat_weight (int, optional) – The weight of the angle constraint concerning flat angles. A high value means those angles will be more likely to keep their value in the resulting polygon.

    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    MAX_ITERATION = 'MAX_ITERATION'
    NORM_TOLERANCE = 'NORM_TOLERANCE'
    RIGHT_TOLERANCE = 'RIGHT_TOLERANCE'
    FLAT_TOLERANCE = 'FLAT_TOLERANCE'
    FIXED_WEIGHT = 'FIXED_WEIGHT'
    RIGHT_WEIGHT = 'RIGHT_WEIGHT'
    FLAT_WEIGHT = 'FLAT_WEIGHT'

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Square Polygon LS'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Buildings'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()
    
    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[1]
        description = self.tr(first_line)
        
        return(description)    

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        return self.tr(f"""
            <b>/!\ If you don't drop Z and M, it won't work ! /!\ </b>
            Squares a polygon using the method of least squares. 
            The least squares based polygon squaring algorithm was proposed by Touya and Lokhat and is particularly useful to square buildings.
            In practice, this function iteratively tries to resolve matrices equations until a threshold norm is reached and the provided constraint are satisfied.
            <h3> Parameters : </h3>
            <ul>
                <li> - <em> Max iteration </em> : Maximum number of iteration before breaking the loop. If constraints and weights are correctly set, the norm tolerance threshold should be reached before the maximum number of iteration. </li>
                <li> - <em> Norm tolerance </em> : The threshold below which the norm of the resulting point matrix is acceptable enough to break the iteration loop.</li>
                <li> - <em> Right tolerance </em> : Tolerance in degrees to consider an angle to be right.</li>
                <li> - <em> Flat tolerance </em> : Tolerance in degrees to consider an angle to be flat.</li>
                <li> - <em> Fixed weight </em> : The weight of the angle constraint concerning an angle neither right nor flat. A high value means those angles will be more likely to keep their value in the resulting polygon. </li>
                <li> - <em> Right weight </em> : The weight of the angle constraint concerning right angles. A high value means those angles will be more likely to keep their value in the resulting polygon. </li>
                <li> - <em> Flat weight </em> : The weight of the angle constraint concerning flat angles. A high value means those angles will be more likely to keep their value in the resulting polygon. </li>
            </ul>
                       
            For more see <a href="https://cartagen.readthedocs.io/en/latest/reference/cartagen.square_polygon_ls.html#cartagen.square_polygon_ls">help online</a>.
            """)
        
    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input buildings :'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        maxiter = QgsProcessingParameterNumber(
            self.MAX_ITERATION,
            self.tr('Max iteration :'),
            type=QgsProcessingParameterNumber.Integer,
            defaultValue=1000,
            optional=False
        )
        self.addParameter(maxiter)

        normtol = QgsProcessingParameterNumber(
            self.NORM_TOLERANCE,
            self.tr('Norm tolerance :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=0.05,
            optional=False
        )
        self.addParameter(normtol)
        
        righttol = QgsProcessingParameterNumber(
            self.RIGHT_TOLERANCE,
            self.tr('Right tolerance :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=10,
            optional=False
        )
        self.addParameter(righttol)

        flattol = QgsProcessingParameterNumber(
            self.FLAT_TOLERANCE,
            self.tr('Flat tolerance :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=10,
            optional=False
        )
        self.addParameter(flattol)

        wfix = QgsProcessingParameterNumber(
            self.FIXED_WEIGHT,
            self.tr('Fixed weight :'),
            type=QgsProcessingParameterNumber.Integer,
            defaultValue=5,
            optional=False
        )
        wfix.setFlags(wfix.flags() | QgsProcessingParameterDefinition.FlagAdvanced)
        self.addParameter(wfix)

        wright = QgsProcessingParameterNumber(
            self.RIGHT_WEIGHT,
            self.tr('Right weight :'),
            type=QgsProcessingParameterNumber.Integer,
            defaultValue=100,
            optional=False
        )
        wright.setFlags(wright.flags() | QgsProcessingParameterDefinition.FlagAdvanced)
        self.addParameter(wright)

        wflat = QgsProcessingParameterNumber(
            self.FLAT_WEIGHT,
            self.tr('Flat weight :'),
            type=QgsProcessingParameterNumber.Integer,
            defaultValue=50,
            optional=False
        )
        wflat.setFlags(wflat.flags() | QgsProcessingParameterDefinition.FlagAdvanced)
        self.addParameter(wflat)

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Squared LS Buildings')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        from cartagen import square_polygon_ls
        from shapely import Polygon
        from shapely.wkt import loads
        import geopandas as gpd
        from cartagen4qgis.src.tools import list_to_qgis_feature_2

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())

        # Create an output sink
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, source.fields(), source.wkbType(), source.sourceCrs())

        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        #Retrieve the parameter values
        maxiter = self.parameterAsInt(parameters, self.MAX_ITERATION, context)
        normtol = self.parameterAsInt(parameters, self.NORM_TOLERANCE, context)
        rtol = self.parameterAsDouble(parameters, self.RIGHT_TOLERANCE, context)
        ftol = self.parameterAsDouble(parameters, self.FLAT_TOLERANCE, context)
        wfixed = self.parameterAsInt(parameters, self.FIXED_WEIGHT, context)
        wright = self.parameterAsInt(parameters, self.RIGHT_WEIGHT, context)
        wflat = self.parameterAsInt(parameters, self.FLAT_WEIGHT, context)

        #Preparing the data and process
        gs = gdf.copy()
        for i in range(len(gdf)):
            geommultiple = gs['geometry'].loc[i]
            listGeomSimple = list(geommultiple.geoms)
            listeTraitee = []

            for ligne in listGeomSimple:
                ligneTraitee = square_polygon_ls(
                    ligne, max_iteration=maxiter, norm_tolerance=normtol, right_tolerance=rtol, flat_tolerance=ftol, fixed_weight=wfixed, right_weight=wright, flat_weight=wflat
                    )
                listeTraitee.append(ligneTraitee)

            gs.loc[i,'geometry'] = listeTraitee

        res = gs.to_dict('records')
        res = list_to_qgis_feature_2(res, source.fields())

        #Create the ouput sink
        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context, 
            res[0].fields(), source.wkbType(), source.sourceCrs())
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {
            self.OUTPUT: dest_id
        }

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return SquaringPolygonLS()


class SquaringPolygonNaive(QgsProcessingAlgorithm):

    """
    Squares a polygon according to its orientation.

    This method, described in Touya, [1] first calculates the orientation of the polygon. Sides are then corrected depending on the angles formed at the vertexes and on their alignment regarding the calculated orientation.

    Parameters:

        polygon (Polygon) – The polygon to square.

        orient (str, optional) –

        The method to calculate the orientation. Be aware that the orientation of the polygon defines how the sides are corrected.

            'primary': calculates the orientation of the longest side of the provided polygon.

            ’mbr’ calculates the orientation of the long side of the minimum rotated bounding rectangle.

            ’mbtr’ calculates the orientation of the long side of the minimum rotated bounding touching rectangle. It is the same as the mbr but the rectangle and the polygon must have at least one side in common.

            ’swo’ or statistical weighted orientation described in Duchêne, [2] calculates the orientation of a polygon using the statistical weighted orientation. This method relies on the length and orientation of the longest and second longest segment between two vertexes of the polygon.

        angle_tolerance (float, optional) – Tolerance in degrees to square the considered angle.

        correct_tolerance (float, optional) – Tolerance in degrees to consider the angle to be already flat or right.

        remove_flat (bool, optional) – If set to True, vertexes with an angle detected or corrected as flat are removed. Thus, the resulting polygon can have less vertexes than the provided one.

    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    ORIENT='ORIENT'
    ANGLE_TOLERANCE='ANGLE_TOLERANCE'
    CORRECT_TOLERANCE='CORRECT_TOLERANCE'
    REMOVE_FLAT='REMOVE_FLAT'

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Square Polygon Naive'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Buildings'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()
    
    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[2]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        return self.tr(f"""
            <b> /!\ If you don't drop Z and M, it won't work ! /!\ </b>
            
            Squares a polygon according to its orientation.
            This method, described in Touya, first calculates the orientation of the polygon. Sides are then corrected depending on the angles formed at the vertexes and on their alignment regarding the calculated orientation.
            
            <h3> Parameters : </h3> 
            <ul>
                <li> - <em> Orientation</em>  : The method to calculate the orientation. Be aware that the orientation of the polygon defines how the sides are corrected :</li>
                <ul>
                    <li>    . <em> 'primary'</em>  calculates the orientation of the longest side of the provided polygon.</li>
                    <li>    . <em> 'mbr'</em> calculates the orientation of the long side of the minimum rotated bounding rectangle.</li>
                    <li>    . <em> 'mbtr'</em> calculates the orientation of the long side of the minimum rotated bounding touching rectangle. It is the same as the mbr but the rectangle and the polygon must have at least one side in common.</li>
                    <li>    . <em> 'swo'</em> or statistical weighted orientation described in Duchêne, calculates the orientation of a polygon using the statistical weighted orientation. This method relies on the length and orientation of the longest and second longest segment between two vertexes of the polygon.</li>
                </ul>
                <li> - <em> Angle tolerance </em> : Tolerance in degrees to square the considered angle.</li>
                <li> - <em> Correct tolerance </em> : Tolerance in degrees to consider the angle to be already flat or right.</li>
                <li> - <em> Remove flat </em> : If set to True, vertexes with an angle detected or corrected as flat are removed. Thus, the resulting polygon can have less vertexes than the provided one.</li>
            </ul>
                       
            For more see <a href="https://cartagen.readthedocs.io/en/latest/reference/cartagen.square_polygon_naive.html#cartagen.square_polygon_naive">help online</a>.
            
            """)
        
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return SquaringPolygonNaive()
    
    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Input buildings :'),
                [QgsProcessing.TypeVectorPolygon]
            )
        )

        listOrient = ['primary', 'mbr', 'mbtr', 'swo']
        orient = QgsProcessingParameterEnum(
            self.ORIENT,
            self.tr('Orientation :'),
            options=listOrient,
            defaultValue='primary',
            optional=False
        )
        self.addParameter(orient)

        angle_tolerance = QgsProcessingParameterNumber(
            self.ANGLE_TOLERANCE,
            self.tr('Angle tolerance :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=8,
            optional=False
        )
        self.addParameter(angle_tolerance)
        
        correct_tolerance = QgsProcessingParameterNumber(
            self.CORRECT_TOLERANCE,
            self.tr('Correct tolerance :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=0.6,
            optional=False
        )
        self.addParameter(correct_tolerance)

        remove_flat = QgsProcessingParameterBoolean(
            self.REMOVE_FLAT,
            self.tr('Remove flat ?'),
            defaultValue=True,
            optional=False
        )
        remove_flat.setFlags(remove_flat.flags() | QgsProcessingParameterDefinition.FlagAdvanced)        
        self.addParameter(remove_flat)

        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Squared Naive Buildings')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        from cartagen import square_polygon_naive
        from shapely import Polygon
        from shapely.wkt import loads
        import geopandas as gpd
        from cartagen4qgis.src.tools import list_to_qgis_feature_2


        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())

        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        #Retrieve the parameter values
        orient = self.parameterAsEnum(parameters, self.ORIENT, context)
        dicoOrient = {0:'primary', 1:'mbr', 2:'mbtr', 3:'swo'}
        angle_tolerance = self.parameterAsDouble(parameters, self.ANGLE_TOLERANCE, context)
        correct_tolerance = self.parameterAsDouble(parameters, self.CORRECT_TOLERANCE, context)
        remove_flat = self.parameterAsBoolean(parameters, self.REMOVE_FLAT, context)

        #Preparing the data and process
        gs = gdf.copy()
        for i in range(len(gdf)):
            geommultiple = gs['geometry'].loc[i]
            listGeomSimple = list(geommultiple.geoms)
            listeTraitee = []

            for ligne in listGeomSimple:
                ligneTraitee = square_polygon_naive(
                    ligne, orient=dicoOrient[orient], angle_tolerance=angle_tolerance, correct_tolerance=correct_tolerance, remove_flat=remove_flat
                )
                listeTraitee.append(ligneTraitee)

            gs.loc[i,'geometry'] = listeTraitee

        res = gs.to_dict('records')
        res = list_to_qgis_feature_2(res, source.fields())

        #Create the ouput sink
        (sink, dest_id) = self.parameterAsSink(
            parameters, self.OUTPUT, context, 
            res[0].fields(), source.wkbType(), source.sourceCrs())
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {
            self.OUTPUT: dest_id
        }
    
class SquarePolygonOrthogonal (QgsProcessingAlgorithm):
    """
            
Squares a building by forcing it into an orthogonal coordinate system.

This algorithm described by Hakim and Tsai [1] is a heuristic approach that leverages the Manhattan World assumption. It identifies the orientation of the building and performs a global rotation to align the footprint with the X/Y grid. Facades are then classified and merged into strictly horizontal or vertical lines. Perfect 90-degree corners are reconstructed via direct line intersections before an inverse rotation is applied to restore the building to its original geospatial location.

Parameters:

        polygon (Polygon) – The polygon to square.

        orientation (str, optional) –

        The method to calculate the orientation of the polygon. This defines the dominant axis used for the global rotation.

            ’primary’ calculates the orientation of the longest side of the provided polygon.

            ’mbr’ calculates the orientation of the long side of the minimum rotated bounding rectangle.

            ’mbtr’ calculates the orientation of the long side of the minimum rotated bounding touching rectangle.

            ’swo’ or statistical weighted orientation calculates the orientation using the statistical weighted orientation method.

        force_all (bool, optional) – If set to True (default), every segment is snapped to whichever cardinal direction (H or V) it is closest to, regardless of the deviation. The angle_tolerance and correct_tolerance parameters are ignored in this mode. Set to False to apply tolerance-based squaring: only segments within angle_tolerance of a cardinal direction are snapped, and vertices already within correct_tolerance of right or flat are left alone.

        angle_tolerance (float, optional) – Only used when force_all is False. Tolerance in degrees within which a segment is snapped to the nearest cardinal direction. Segments whose deviation exceeds this value are left unchanged (‘U’).

        correct_tolerance (float, optional) – Only used when force_all is False. Tolerance in degrees below which a vertex is considered already correct and skipped.

        remove_flat (bool, optional) – If set to True, vertices whose interior angle is flat (close to 180°) after squaring are removed from the result.

Returns:

    Polygon


    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'
    ORIENTATION='ORIENTATION'
    FORCE_ALL='FORCE_ALL'
    ANGLE_TOLERANCE='ANGLE_TOLERANCE'
    CORRECT_TOLERANCE='CORRECT_TOLERANCE'
    REMOVE_FLAT='REMOVE_FLAT'

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Square Polygon Orthogonal'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Buildings'

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        from cartagen4qgis import get_plugin_icon
        return get_plugin_icon()

    def shortDescription(self):
        """
        Returns an optional translated short description of the algorithm. This 
        should be at most a single sentence, e.g. “Converts 2D features to 3D by 
        sampling a DEM raster.”
        """
        first_line = self.shortHelpString().strip().splitlines()[0]
        description = self.tr(first_line)
        
        return(description)

    def shortHelpString(self):
        """
        Returns a localised short helper string for the algorithm. This string
        should provide a basic description about what the algorithm does and the
        parameters and outputs associated with it..
        """
        helpstring = """
        Squares a building by forcing it into an orthogonal coordinate system.
 This algorithm described by Hakim and Tsai [1] is a heuristic approach that leverages the Manhattan World assumption. It identifies the orientation of the building and performs a global rotation to align the footprint with the X/Y grid. Facades are then classified and merged into strictly horizontal or vertical lines. Perfect 90-degree corners are reconstructed via direct line intersections before an inverse rotation is applied to restore the building to its original geospatial location. Parameters: The method to calculate the orientation of the polygon. This defines the dominant axis used for the global rotation. ’primary’ calculates the orientation of the longest side of the provided polygon. ’mbr’ calculates the orientation of the long side of the minimum rotated bounding rectangle. ’mbtr’ calculates the orientation of the long side of the minimum rotated bounding touching rectangle.
         <h3> Parameters: </h3>
        <ul>
          <li> - <em>Orientation </em> :  </li>
          The method to calculate the orientation of the polygon. This defines the dominant axis used for the global rotation.
                . ’primary’ calculates the orientation of the longest side of the provided polygon.
                . ’mbr’ calculates the orientation of the long side of the minimum rotated bounding rectangle.
                . ’mbtr’ calculates the orientation of the long side of the minimum rotated bounding touching rectangle.
                . ’swo’ or statistical weighted orientation calculates the orientation using the statistical weighted orientation method.

          <li> - <em>Force_all </em> :  If set to True (default), every segment is snapped to whichever cardinal direction (H or V) it is closest to, regardless of the deviation. The angle_tolerance and correct_tolerance parameters are ignored in this mode. Set to False to apply tolerance-based squaring: only segments within angle_tolerance of a cardinal direction are snapped, and vertices already within correct_tolerance of right or flat are left alone. </li>
          <li> - <em>Angle_tolerance </em> :  Only used when force_all is False. Tolerance in degrees within which a segment is snapped to the nearest cardinal direction. Segments whose deviation exceeds this value are left unchanged (‘U’). </li>
          <li> - <em>Correct_tolerance </em> :  Only used when force_all is False. Tolerance in degrees below which a vertex is considered already correct and skipped. </li>
          <li> - <em>Remove_flat </em> :  If set to True, vertices whose interior angle is flat (close to 180°) after squaring are removed from the result. </li>
        </ul>
            For more see <a href="https://cartagen.readthedocs.io/en/main/reference/cartagen.square_polygon_orthogonal.html#cartagen.square_polygon_orthogonal">help online</a>.
            
        """
        
        return self.tr(helpstring)
    
    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return SquarePolygonOrthogonal()

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """
                
        # We add the input vector features source.
        input = QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr(' The polygon to square. :'),
                [QgsProcessing.TypeVectorPolygon]
            )
        self.addParameter(input)
        
        orientations = ['mbtr','primary', 'mbr', 'swo']
        orientation = QgsProcessingParameterEnum(
            self.ORIENTATION,
            self.tr('Orientation :'),
            orientations,
            defaultValue = "mbtr"
        )
        self.addParameter(orientation)
                
        force_all = QgsProcessingParameterBoolean(
            self.FORCE_ALL,
            self.tr('Force_all ?'),
            defaultValue=True,
            optional=False
        )
        self.addParameter(force_all)
            
        angle_tolerance = QgsProcessingParameterNumber(
            self.ANGLE_TOLERANCE,
            self.tr('Angle tolerance :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=1,
            optional=False
        )
        self.addParameter(angle_tolerance)
        
        correct_tolerance = QgsProcessingParameterNumber(
            self.CORRECT_TOLERANCE,
            self.tr('Correct tolerance :'),
            type=QgsProcessingParameterNumber.Double,
            defaultValue=1,
            optional=False
        )
        self.addParameter(correct_tolerance)
        
        remove_flat = QgsProcessingParameterBoolean(
            self.REMOVE_FLAT,
            self.tr('Remove flat ?'),
            defaultValue=True,
            optional=False
        )
        self.addParameter(remove_flat)
            
        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).   
        output = QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Squared Polygon Orthogonal'))
        self.addParameter(output)

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        import geopandas as gpd
        import pandas
        from cartagen import square_polygon_orthogonal
        from cartagen4qgis.src.tools import list_to_qgis_feature_2

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)
        gdf = gpd.GeoDataFrame.from_features(source.getFeatures())
        
        # retrieve the other parameters values

        orientations = ['primary', 'mbr', 'mbtr', 'swo']
        orientation = self.parameterAsEnum(parameters, self.ORIENTATION, context)
            
        force_all = self.parameterAsBoolean(parameters, self.FORCE_ALL, context)
            
        angle_tolerance = self.parameterAsDouble(parameters, self.ANGLE_TOLERANCE, context)
            
        correct_tolerance = self.parameterAsDouble(parameters, self.CORRECT_TOLERANCE, context)
            
        remove_flat = self.parameterAsBoolean(parameters, self.REMOVE_FLAT, context)
            
        
        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        dp = gdf.copy()
        for i in range(len(gdf)):
            dp.loc[i,'geometry'] = square_polygon_orthogonal (list(gdf.geometry)[i], orientation=orientations[orientation],force_all=force_all,angle_tolerance=angle_tolerance,correct_tolerance=correct_tolerance,remove_flat=remove_flat)

            # Update the progress bar
            feedback.setProgress(int(i * total))

        res = dp.to_dict('records')
        res = list_to_qgis_feature_2(res,source.fields())

        # Create the output sink    
        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, res[0].fields(), source.wkbType(), source.sourceCrs())
        
        # Add a feature in the sink
        sink.addFeatures(res, QgsFeatureSink.FastInsert)
        
        return {
            self.OUTPUT: dest_id
            }
        