# -*- coding: utf-8 -*-

"""
/***************************************************************************
CartAGen4QGIS
A QGIS plugin
Cartographic generalization
Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
-------------------
        begin                : 2023-05-11
        copyright            : (C) 2023 by Guillaume Touya, Justin Berli & Paul Bourcier
        email                : guillaume.touya@ign.fr
 ***************************************************************************/
"""

__author__ = 'Guillaume Touya, Justin Berli & Paul Bourcier'
__date__ = '2023-05-11'
__copyright__ = '(C) 2023 by Guillaume Touya, Justin Berli & Paul Bourcier'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
from qgis.core import QgsProcessingProvider
from qgis.PyQt.QtGui import QIcon

class CartAGen4QGISProvider(QgsProcessingProvider):

    def __init__(self):
        """
        Default constructor.
        """
        QgsProcessingProvider.__init__(self)
        self._icon = None
        self._algorithms_loaded = False

    def unload(self):
        """
        Unloads the provider. Any tear-down steps required by the provider
        should be implemented here.
        """
        self._icon = None
        self._algorithms_loaded = False

    def loadAlgorithms(self):
        """
        Loads all algorithms belonging to this provider.
        """
        # Éviter de charger plusieurs fois
        if self._algorithms_loaded:
            return
        
        from .algorithms import (

            #Boundaries
            BoundariesDouglasPeucker,
            BoundariesRaposo,
            BoundariesLiOpenshaw,
            BoundariesVisvalingam,

            #Buildings
            BoffetArea,
            ClosePolygon,
            MorphologicalAmalgamation,
            BuildingFER,
            BuildingRectangle,
            BuildingRegression,
            BuildingSimplificationRuasQGIS,
            BuildingDisplacementRandomQGIS,
            SquaringPolygonLS,
            SquaringPolygonNaive,

            #Network
            BuildStrokes,
            CollapseRoundaboutsQGIS,
            CollapseBranchingCrossroads,
            CollapseDualCarriageways,
            DetectRoundaboutsQGIS,
            DetectDeadEnds,
            DetectBranchingCrossroads,
            EliminateDeadEnds,
            DetectDualCarriageways,
            RuralTraffic,

            #Partitioning
            NetworkFacesQGIS,

            #Points
            VectorHeatmap,
            HullDelaunay,
            HullSwingingArm,
            ReduceKmeans,
            ReduceLabelgrid,
            ReduceQuadtree,

            #Simplify
            SimplifyAngular,
            DouglasPeucker,
            Lang,
            LiOpenshaw,
            RaposoSimplificationQGIS,
            ReumannWitkam,
            VisvalingamWhyattQGIS,
            SimplifyWangMuller,
            Whirlpool,

            #Skeletonize And Spinalize
            SkelNatural,
            SkelArtificial,
            SkelNetwork,
            
            #Smooth
            CatmullRomSmoothing,
            ChaikinSmoothing,
            GaussianSmoothing,
            SmoothPlatre,
            SmoothSnake,
            SmoothTaubin,
            SmoothTopographic,
            SmoothWMA

        )

        #Boundaries
        self.addAlgorithm(BoundariesDouglasPeucker())
        self.addAlgorithm(BoundariesLiOpenshaw())
        self.addAlgorithm(BoundariesRaposo())
        self.addAlgorithm(BoundariesVisvalingam())

        # Buildings
        self.addAlgorithm(SquaringPolygonLS())
        self.addAlgorithm(SquaringPolygonNaive())
        self.addAlgorithm(BuildingSimplificationRuasQGIS())
        self.addAlgorithm(BuildingDisplacementRandomQGIS())
        self.addAlgorithm(MorphologicalAmalgamation())
        self.addAlgorithm(BoffetArea())
        self.addAlgorithm(ClosePolygon())
        self.addAlgorithm(BuildingFER())
        self.addAlgorithm(BuildingRectangle())
        self.addAlgorithm(BuildingRegression())
        
        # Network
        self.addAlgorithm(BuildStrokes())
        self.addAlgorithm(DetectRoundaboutsQGIS())
        self.addAlgorithm(DetectDeadEnds())
        self.addAlgorithm(EliminateDeadEnds())
        self.addAlgorithm(CollapseRoundaboutsQGIS())
        self.addAlgorithm(DetectBranchingCrossroads())
        self.addAlgorithm(CollapseBranchingCrossroads())
        self.addAlgorithm(DetectDualCarriageways())
        self.addAlgorithm(CollapseDualCarriageways())
        self.addAlgorithm(RuralTraffic())

        # Partitioning
        self.addAlgorithm(NetworkFacesQGIS())
        
        # Points
        self.addAlgorithm(ReduceKmeans())
        self.addAlgorithm(ReduceLabelgrid())
        self.addAlgorithm(ReduceQuadtree())
        self.addAlgorithm(HullDelaunay())
        self.addAlgorithm(HullSwingingArm())
        self.addAlgorithm(VectorHeatmap())

        # Processes
        # self.addAlgorithm(ConstraintMethodQGIS())

        # Simplify
        self.addAlgorithm(SimplifyAngular())
        self.addAlgorithm(DouglasPeucker())
        self.addAlgorithm(Lang())
        self.addAlgorithm(LiOpenshaw())
        self.addAlgorithm(RaposoSimplificationQGIS())
        self.addAlgorithm(ReumannWitkam())
        self.addAlgorithm(VisvalingamWhyattQGIS())
        self.addAlgorithm(SimplifyWangMuller())
        self.addAlgorithm(Whirlpool())

        #Skeletonize and Spinalize
        self.addAlgorithm(SkelNatural())
        self.addAlgorithm(SkelArtificial())
        self.addAlgorithm(SkelNetwork())
        
        #Smooth
        self.addAlgorithm(GaussianSmoothing())
        self.addAlgorithm(CatmullRomSmoothing())
        self.addAlgorithm(ChaikinSmoothing())
        self.addAlgorithm(SmoothPlatre())
        self.addAlgorithm(SmoothSnake())
        self.addAlgorithm(SmoothTaubin())
        self.addAlgorithm(SmoothTopographic())
        self.addAlgorithm(SmoothWMA())
                
        self._algorithms_loaded = True

    def id(self):
        """
        Returns the unique provider id, used for identifying the provider. This
        string should be a unique, short, character only string, eg "qgis" or
        "gdal". This string should not be localised.
        """
        return 'CartAGen'

    def name(self):
        """
        Returns the provider name, which is used to describe the provider
        within the GUI.

        This string should be short (e.g. "Lastools") and localised.
        """
        return self.tr('CartAGen')

    def icon(self):
        """
        Should return a QIcon which is used for your provider inside
        the Processing toolbox.
        """
        # Hide the icon to avoid recreating it every time
        if self._icon is None:
            try:
                # Try to koad the icon from the parent module
                from cartagen4qgis import get_plugin_icon
                self._icon = get_plugin_icon()
            except Exception:
                # In case of error, return empty icon to avoid crash
                try:
                    self._icon = QIcon()
                except:
                    return QIcon()
        
        return self._icon

    def longName(self):
        """
        Returns the a longer version of the provider name, which can include
        extra details such as version numbers. E.g. "Lastools LIDAR tools
        (version 2.2.1)". This string should be localised. The default
        implementation returns the same string as name().
        """
        return self.name()